export const companiesTexts = {
  title: 'Compañías',
  search: 'Buscar compañías',
  newCompany: 'Nueva Compañía',
  editCompany: 'Editar Compañía',
  successfullyCreated: 'Compañía creada con éxito',
  successfullyUpdated: 'Compañía actualizada con éxito',
  successfullyDeleted: 'Compañía eliminada con éxito',
  successfullyRestored: 'Compañía restaurada con éxito',
  deleteConfirmation: '¿Estás seguro de que quieres eliminar esta compañía?',
  restoreConfirmation: '¿Estás seguro de que quieres restaurar esta compañía?',
  delete: 'Eliminar',
  restore: 'Restaurar',
  cancel: 'Cancelar',
  active: 'Activo',
  inactive: 'Inactivo',
  actions: 'Acciones',
  name: 'Nombre',
  ruc: 'RUC',
  status: 'Estado',
  creationDate: 'Fecha de Creación',
};
