export const companiesTexts = {
  title: 'Compañías',
  search: 'Buscar compañías',
  newCompany: 'Nueva Compañía',
  editCompany: 'Editar Compañía',
  successfullyCreated: 'Compañía creada con éxito',
  successfullyUpdated: 'Compañía actualizada con éxito',
  successfullyDeactivated: 'Compañía desactivada con éxito',
  successfullyActivated: 'Compañía activada con éxito',
  deactivateConfirmation: '¿Estás seguro de que quieres desactivar esta compañía?',
  activateConfirmation: '¿Estás seguro de que quieres activar esta compañía?',
  deactivate: 'Desactivar',
  activate: 'Activar',
  cancel: 'Cancelar',
  active: 'Activo',
  inactive: 'Inactivo',
  actions: 'Acciones',
  name: 'Nombre',
  ruc: 'RUC',
  status: 'Estado',
  creationDate: 'Fecha de Creación',
};
